export { default as handleOpen } from './mappings/book-manager/open'
export { default as handleMake } from './mappings/book-manager/make'
export { default as handleTake } from './mappings/book-manager/take'
export { default as handleClaim } from './mappings/book-manager/claim'
export { default as handleCancel } from './mappings/book-manager/cancel'
export { default as handleTransfer } from './mappings/book-manager/transfer'
